name: hackntu_week02
channels:
- defaults
dependencies:
- bleach=1.5.0=py36_0
- cairo=1.14.8=0
- cycler=0.10.0=py36_0
- dbus=1.10.10=0
- decorator=4.0.11=py36_0
- entrypoints=0.2.2=py36_1
- expat=2.1.0=0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- glib=2.50.2=1
- graphviz=2.38.0=4
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- harfbuzz=0.9.39=2
- html5lib=0.999=py36_0
- icu=54.1=0
- ipykernel=4.5.2=py36_0
- ipython=5.3.0=py36_0
- ipython_genutils=0.1.0=py36_0
- jbig=2.1=0
- jinja2=2.9.5=py36_0
- jpeg=9b=0
- jsonschema=2.5.1=py36_0
- jupyter_client=5.0.0=py36_0
- jupyter_core=4.3.0=py36_0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libiconv=1.14=0
- libpng=1.6.27=0
- libsodium=1.0.10=0
- libtiff=4.0.6=3
- libtool=2.4.2=0
- libxcb=1.12=1
- libxml2=2.9.4=0
- markupsafe=0.23=py36_2
- matplotlib=2.0.0=np112py36_0
- mistune=0.7.3=py36_0
- mkl=2017.0.1=0
- nbconvert=5.1.1=py36_0
- nbformat=4.3.0=py36_0
- notebook=4.3.1=py36_0
- numpy=1.12.0=py36_0
- olefile=0.44=py36_0
- openssl=1.0.2k=1
- pandocfilters=1.4.1=py36_0
- pango=1.40.3=1
- path.py=10.1=py36_0
- pcre=8.39=1
- pexpect=4.2.1=py36_0
- pickleshare=0.7.4=py36_0
- pillow=4.0.0=py36_1
- pip=9.0.1=py36_1
- pixman=0.34.0=0
- prompt_toolkit=1.0.9=py36_0
- ptyprocess=0.5.1=py36_0
- pygments=2.2.0=py36_0
- pyparsing=2.1.4=py36_0
- pyqt=5.6.0=py36_2
- python=3.6.0=0
- python-dateutil=2.6.0=py36_0
- pytz=2016.10=py36_0
- pyzmq=16.0.2=py36_0
- qt=5.6.2=3
- readline=6.2=2
- scikit-learn=0.18.1=np112py36_1
- scipy=0.18.1=np112py36_1
- setuptools=27.2.0=py36_0
- simplegeneric=0.8.1=py36_1
- sip=4.18=py36_0
- six=1.10.0=py36_0
- sqlite=3.13.0=0
- terminado=0.6=py36_0
- testpath=0.3=py36_0
- tk=8.5.18=0
- tornado=4.4.2=py36_0
- traitlets=4.3.2=py36_0
- wcwidth=0.1.7=py36_0
- wheel=0.29.0=py36_0
- xz=5.2.2=1
- zeromq=4.1.5=0
- zlib=1.2.8=3
- pip:
  - ipython-genutils==0.1.0
  - jupyter-client==5.0.0
  - jupyter-core==4.3.0
  - prompt-toolkit==1.0.9
  - pydot-ng==1.0.0
